name: iOS build & deploy to App Store Connect

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: macos-latest
        env:
            BUNDLE_ID: com.peterandlinda.iOCNews
        steps:
            - uses: actions/checkout@v3.3.0

            - name: Set up ruby env
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: '3.1.2'

            - name: Install ruby dependencies
              run: bundle install

            # Can be used to specify an older or beta version of Xcode if needed
            - name: Setup Xcode version
              uses: maxim-lobanov/setup-xcode@v1.5.1
              with:
                  xcode-version: latest-stable

            - name: Install package dependencies via cocoapods
              run: pod install

            - name: Decode signing certificate into a file
              env:
                  CERTIFICATE_BASE64: ${{ secrets.IOS_DIST_SIGNING_KEY }}
              run: |
                  echo $CERTIFICATE_BASE64 | base64 --decode > signing-cert.p12

            - name: Build & deploy the app using fastlane
              run: bundle exec fastlane ios build_deploy
              env:
                  ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
                  ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
                  ASC_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
                  SIGNING_KEY_PASSWORD: ${{ secrets.IOS_DIST_SIGNING_KEY_PASSWORD }}
                  SIGNING_KEY_FILE_PATH: signing-cert.p12

            - name: Upload ipa and dsyms to artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: app-store binary
                  path: |
                      ${{ github.workspace }}/*.ipa
                      ${{ github.workspace }}/*.app.dSYM.zip
